//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        public Adresa()
        {
            this.Covjek = new HashSet<Covjek>();
            this.Dzemati = new HashSet<Dzemati>();
        }
    
        public int id { get; set; }
        public string grad { get; set; }
        public string drzava { get; set; }
        public string broj { get; set; }
        public string postanskiBroj { get; set; }
    
        public virtual ICollection<Covjek> Covjek { get; set; }
        public virtual ICollection<Dzemati> Dzemati { get; set; }
    }
}
