//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cabmanagementEntities3 : DbContext
    {
        public cabmanagementEntities3()
            : base("name=cabmanagementEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CABTimes> CABTimes { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<tblAttachments> tblAttachments { get; set; }
        public DbSet<tblCAB> tblCAB { get; set; }
        public DbSet<tblCABAnalysis> tblCABAnalysis { get; set; }
        public DbSet<tblCABCodeReview> tblCABCodeReview { get; set; }
        public DbSet<tblCABComment> tblCABComment { get; set; }
        public DbSet<tblCABHistory> tblCABHistory { get; set; }
        public DbSet<tblCABSchedules> tblCABSchedules { get; set; }
        public DbSet<tblCABStartEnd> tblCABStartEnd { get; set; }
        public DbSet<tblCABTaska> tblCABTaska { get; set; }
        public DbSet<tblCABTaskaH> tblCABTaskaH { get; set; }
        public DbSet<tblCABTesting> tblCABTesting { get; set; }
        public DbSet<tblCABVoting> tblCABVoting { get; set; }
        public DbSet<tblDevelopers> tblDevelopers { get; set; }
        public DbSet<tblDevelopersTimes> tblDevelopersTimes { get; set; }
        public DbSet<tblStatusi> tblStatusi { get; set; }
        public DbSet<tblTaskHistory> tblTaskHistory { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
        public DbSet<TraceLog> TraceLog { get; set; }
    }
}
