//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covjek
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public Nullable<int> adresaId { get; set; }
        public Nullable<bool> isImam { get; set; }
        public Nullable<bool> isReis { get; set; }
        public Nullable<bool> isUpravniOdbor { get; set; }
    
        public virtual Adresa Adresa { get; set; }
    }
}
