//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dzemati
    {
        public int id { get; set; }
        public string naziv { get; set; }
        public int adresaId { get; set; }
        public string email { get; set; }
        public Nullable<int> brojDzamija { get; set; }
    
        public virtual Adresa Adresa { get; set; }
    }
}
