//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mirnesEntities1 : DbContext
    {
        public mirnesEntities1()
            : base("name=mirnesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adresa> Adresa { get; set; }
        public DbSet<Covjek> Covjek { get; set; }
        public DbSet<Dzemati> Dzemati { get; set; }
        public DbSet<Korisnici> Korisnici { get; set; }
    }
}
