//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachments
    {
        public int AttachID { get; set; }
        public int CAB_HD_No { get; set; }
        public string Attach_Address { get; set; }
    
        public virtual tblCAB tblCAB { get; set; }
    }
}
