//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCABAnalysis
    {
        public tblCABAnalysis()
        {
            this.tblCABHistory = new HashSet<tblCABHistory>();
        }
    
        public int AnalyzeID { get; set; }
        public int CAB_HD_No { get; set; }
        public string AnalyzerID { get; set; }
        public Nullable<int> PredictedWH { get; set; }
        public string AnalyzeText { get; set; }
    
        public virtual tblCAB tblCAB { get; set; }
        public virtual tblDevelopers tblDevelopers { get; set; }
        public virtual ICollection<tblCABHistory> tblCABHistory { get; set; }
    }
}
