//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCABTesting
    {
        public int ID { get; set; }
        public int CAB_HD_No { get; set; }
        public string Status_Test { get; set; }
        public Nullable<System.DateTime> Datum_Izmjene { get; set; }
        public string Opis { get; set; }
        public string DeveloperID { get; set; }
    
        public virtual tblCAB tblCAB { get; set; }
    }
}
