//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCABComment
    {
        public int ID { get; set; }
        public int CAB_HD_No { get; set; }
        public string DeveloperID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int StatusID { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        public virtual tblCAB tblCAB { get; set; }
        public virtual tblDevelopers tblDevelopers { get; set; }
        public virtual tblStatusi tblStatusi { get; set; }
    }
}
