//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCAB
    {
        public tblCAB()
        {
            this.tblAttachments = new HashSet<tblAttachments>();
            this.tblCABAnalysis = new HashSet<tblCABAnalysis>();
            this.tblCABComment = new HashSet<tblCABComment>();
            this.tblCABHistory = new HashSet<tblCABHistory>();
            this.tblCABStartEnd = new HashSet<tblCABStartEnd>();
            this.tblCABTesting = new HashSet<tblCABTesting>();
        }
    
        public int CAB_HD_No { get; set; }
        public int CAB_Id { get; set; }
        public string CAB_Type { get; set; }
        public Nullable<System.DateTime> CAB_HD_Date { get; set; }
        public string CAB_HD_Title { get; set; }
        public string CAB_Sender { get; set; }
        public string CAB_Priority { get; set; }
        public string CAB_Note { get; set; }
        public string Developer_Comment { get; set; }
        public string CAB_Department { get; set; }
    
        public virtual ICollection<tblAttachments> tblAttachments { get; set; }
        public virtual ICollection<tblCABAnalysis> tblCABAnalysis { get; set; }
        public virtual ICollection<tblCABComment> tblCABComment { get; set; }
        public virtual ICollection<tblCABHistory> tblCABHistory { get; set; }
        public virtual ICollection<tblCABStartEnd> tblCABStartEnd { get; set; }
        public virtual ICollection<tblCABTesting> tblCABTesting { get; set; }
    }
}
