//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CABManagementAPICall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskHistory
    {
        public int TaskHistoryID { get; set; }
        public int CAB_TASK_ID { get; set; }
        public string DeveloperID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
